import './global.css';
import { ChakraProviders } from './providers';
import {QueryProvider} from './QueryClientProvider'

export const metadata = {
  title: 'Welcome to ticketmaster',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <html lang="en">
      <body>
      <QueryProvider>
        <ChakraProviders>{children}</ChakraProviders>
        </QueryProvider>
      </body>
    </html>


  );
}
